// Generated by ts-to-zod
import { z } from "zod";

export const linkSchema = z.object({
  label: z.string(),
  href: z.string().url(),
});

export const socialLinkSchema = linkSchema.and(
  z.object({
    icon: z.string(),
  })
);

export const projectSchema = z.object({
  name: z.string(),
  yearReleased: z.number(),
  description: z.string(),
  cover: z.string().url(),
  href: z.string().url(),
});

export const articleSchema = z.object({
  title: z.string(),
  description: z.string(),
  url: z.string().url(),
  social_image: z.string().url(),
});

export const articleListSchema = z.array(articleSchema);

export const configSchema = z.object({
  name: z.string(),
  roles: z.array(z.string()),
  social: z.array(socialLinkSchema),
  aboutMe: z.string().url(),
  avatar: z.string().url(),
  projects: z.array(projectSchema),
  devToUser: z.string().nullable(),
});
